language: ruby
rvm:
  - 2.7.0

before_install:
  # Bundler 2.0 support
  # See: https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - gem update --system
  - gem install jekyll bundler

script:
  # Build Jekyll site
  - bundle exec jekyll build

deploy:
  # Cleanup removes keys and build artefacts.
  # See: https://docs.travis-ci.com/user/deployment/#Uploading-Files-and-skip_cleanup
  skip_cleanup: true
  provider: script
  script: bash .distributed-press/deploy.sh $api_staging 
  on:
    branch:
      - deploy-staging

notifications:
  email: false
