language: ruby
rvm:
  - 2.7.0

before_install:
  # Bundler 2.0 support
  # See: https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - gem update --system
  - gem install jekyll bundler

script:
  # Build Jekyll site
  - bundle install
  - bundle exec jekyll build

deploy:
  # Cleanup removes keys and build artefacts.
  # See: https://docs.travis-ci.com/user/deployment/#Uploading-Files-and-skip_cleanup
  skip_cleanup: true
  provider: script
  script: tar -czvf www.tar.gz -C _site . && bash -x .distributed-press/deploy.sh $api_staging ./.distributed-press/config.staging.json www.tar.gz && bash -x .distributed-press/deploy.sh $api_prod ./.distributed-press/config.prod.json www.tar.gz
  on:
    branch:
      - master

notifications:
  email: false
